#ifndef MAZE_H
#define MAZE_H

#include <QGraphicsScene>

#define GHOST_NUMBERS   4

enum
{
    noItem,
    smallPoint,
    bigPoint,
    error = 255
};

class Maze
{
public:
    Maze(QGraphicsScene *scPointer);
    void paint(void);
    int getDots(QPoint position);
    void setDots(QPoint position, int item);
    std::vector<QPoint> getMaze(QPoint position);
    const static int width = 28;
    const static int height = 36;



private:
    QGraphicsScene *sc;
    int dots[height][width] = {
        {noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem},
        {noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem},
        {noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem},
        {noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem},
        {noItem, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, noItem, noItem, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, noItem},
        {noItem, smallPoint, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, smallPoint, noItem},
        {noItem, bigPoint, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, bigPoint, noItem},
        {noItem, smallPoint, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, smallPoint, noItem},
        {noItem, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, noItem},
        {noItem, smallPoint, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, smallPoint, noItem},
        {noItem, smallPoint, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, smallPoint, noItem},
        {noItem, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, noItem, noItem, smallPoint, smallPoint, smallPoint, smallPoint, noItem, noItem, smallPoint, smallPoint, smallPoint, smallPoint, noItem, noItem, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, noItem},
        {noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem},
        {noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem},
        {noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem},
        {noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem},
        {noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem},
        {noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem},
        {noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem},
        {noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem},
        {noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem},
        {noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem},
        {noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem},
        {noItem, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, noItem, noItem, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, noItem},
        {noItem, smallPoint, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, smallPoint, noItem},
        {noItem, smallPoint, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, smallPoint, noItem},
        {noItem, bigPoint, smallPoint, smallPoint, noItem, noItem, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, noItem, noItem, smallPoint, smallPoint, bigPoint, noItem},
        {noItem, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, noItem},
        {noItem, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, noItem},
        {noItem, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, noItem, noItem, smallPoint, smallPoint, smallPoint, smallPoint, noItem, noItem, smallPoint, smallPoint, smallPoint, smallPoint, noItem, noItem, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, noItem},
        {noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem},
        {noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem, noItem, smallPoint, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, smallPoint, noItem},
        {noItem, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, smallPoint, noItem},
        {noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem},
        {noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem},
        {noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem, noItem},
        };

    std::vector<QPoint> maze[height][width] = {
        {{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
        {{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
        {{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
        {{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
        {{}, {QPoint(1.0, 0), QPoint(0, 1.0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0), QPoint(0, 1.0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(0, 1.0)}, {}, {}, {QPoint(1.0, 0), QPoint(0, 1.0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0), QPoint(0, 1.0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(0, 1.0)}, {}},
        {{}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}},
        {{}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}},
        {{}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}},
        {{}, {QPoint(0, -1.0), QPoint(0, 1.0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(0, 1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0), QPoint(0, 1.0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0), QPoint(0, 1.0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(0, 1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(0, 1.0), QPoint(-1.0, 0)}, {}},
        {{}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}},
        {{}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}},
        {{}, {QPoint(0, -1.0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(0, 1.0), QPoint(-1.0, 0)}, {}, {}, {QPoint(0, -1.0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(0, 1.0)}, {}, {}, {QPoint(1.0, 0), QPoint(0, 1.0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0)}, {}},
        {{}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}},
        {{}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}},
        {{}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(1.0, 0), QPoint(0, 1.0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}},
        {{}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}},
        {{}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}},
        {{QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(0, 1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(0, 1.0), QPoint(-1.0, 0)}, {}, {}, {}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(0, 1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}},
        {{}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}},
        {{}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}},
        {{}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(0, 1.0), QPoint(-1.0, 0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}},
        {{}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}},
        {{}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}},
        {{}, {QPoint(1.0, 0), QPoint(0, 1.0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(0, 1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(0, 1.0)}, {}, {}, {QPoint(1.0, 0), QPoint(0, 1.0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(0, 1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(0, 1.0)}, {}},
        {{}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}},
        {{}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}},
        {{}, {QPoint(0, -1.0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0), QPoint(0, 1.0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0), QPoint(0, 1.0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(0, 1.0), QPoint(-1.0, 0)}, {}, {}, {QPoint(1.0, 0), QPoint(0, 1.0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0)}, {}},
        {{}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}},
        {{}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}},
        {{}, {QPoint(1.0, 0), QPoint(0, 1.0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0)}, {}, {}, {QPoint(0, -1.0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(0, 1.0)}, {}, {}, {QPoint(1.0, 0), QPoint(0, 1.0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0)}, {}, {}, {QPoint(0, -1.0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(0, 1.0)}, {}},
        {{}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}},
        {{}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {QPoint(0, -1.0), QPoint(0, 1.0)}, {}},
        {{}, {QPoint(0, -1.0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(-1.0, 0), QPoint(1.0, 0)}, {QPoint(0, -1.0), QPoint(-1.0, 0)}, {}},
        {{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
        {{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
        {{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
        };

};

#endif // MAZE_H
