name: Windows Release Build

# Set Workflow to verify all changes made to main branch.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
# Choose terminal application to use.
defaults:
  run:
    shell: cmd

# Set required enviroment variables.
env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.4.3
  ARTIFACT:     windows-build
  BUILD_TYPE:   Release

# Build the project, run test cases and save 
# deployed build output as artifact.
jobs:
  build-and-test:
    runs-on:  windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get all tags for correct version determination
        working-directory:  ${{ github.workspace }}
        run: |
          git fetch --all --tags -f
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version:      ${{ env.QT_VERSION }}
          host:         windows
          target:       desktop
          arch:         win64_mingw
          dir:          ${{ runner.temp }}
          setup-python: false

      - name: install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.16.x'
      
      - name: Create build directory
        run:  mkdir ${{ runner.temp }}\build

      #- name: Set up Visual Studio shell
      #  uses: egor-tensin/vs-shell@v2
      #  with:
      #    arch: x64

      - name: Build and deploy
        working-directory: ${{ runner.temp }}\build
        run:  |
          cd ${{github.workspace}}/PacMan/
          cmake -S . -B ${{ runner.temp }}\build -G Ninja
          cmake --build ${{ runner.temp }}\build --config ${{env.BUILD_TYPE}} --target clean
          windeployqt ${{ runner.temp }}\build
          
      - name: Test
        working-directory: ${{ runner.temp }}\build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
        
      - name: Save build artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}\build\
